[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicy = "on_failure"
numReplicas = 1

[variables]
NODE_ENV = "production" 